const axios = require("axios");
const nsfwarray = [
  "nsfwmenu",
  "spreadpussy",
  "genshin",
  "squirt",
  "glasses",
  "sunglasses",
  "swimsuit",
  "schoolswimsuit",
  "hololive",
  "ass",
  "underwear",
  "nipples",
  "uncensored",
  "sex",
  "sex2",
  "sex3",
  "blonde",
  "twintails",
  "breasts",
  "thighhighs",
  "skirt",
  "gamecg",
  "animalears",
  "foxgirl",
  "dress",
  "schooluniform",
  "twogirls",
  "gloves",
  "vocaloid",
  "touhou",
  "weapon",
  "withflowers",
  "pinkhair",
  "cloudsview",
  "white",
  "animal",
  "tail",
  "nude",
  "ponytail",
  "bed",
  "whitehair",
  "ribbons",
  "japanesecloths",
  "hatsuneAtlas",
  "bikini",
  "barefoot",
  "nobra",
  "food",
  "wings",
  "pantyhose",
  "openshirt",
  "headband",
  "penis",
  "close",
  "wet",
  "catgirl",
  "wolfgirl",
  "hneko",
  "hloli",
  "spreadlegs",
  "bra",
  "fateseries",
  "tree",
  "elbowgloves",
  "greenhair",
  "horns",
  "withpetals",
  "drunk",
  "cum",
  "headdress",
  "tie",
  "shorts",
  "hmaid",
  "headphones",
  "anusview",
  "Idol",
  "gun",
  "stockings",
  "tears",
  "breasthold",
  "necklace",
  "seethrough",
  "bunnyears",
  "bunnygirl",
  "topless",
  "beach",
  "erectnipples",
  "yuri",
  "vampire",
  "shirt",
  "pantypull",
  "tornclothes",
  "bondage",
  "demon",
  "bell",
  "shirtlift",
  "tattoo",
  "chain",
  "flatchest",
  "fingering",
];
module.exports = {
  name: "nsfwimages",
  alias: [...nsfwarray],
  uniquecommands: [
    "nsfwmenu",
    "spreadpussy",
    "genshin",
    "squirt",
    "glasses",
    "sunglasses",
    "swimsuit",
    "schoolswimsuit",
    "hololive",
    "ass",
    "underwear",
    "nipples",
    "uncensored",
    "sex",
    "sex2",
    "sex3",
    "blonde",
    "twintails",
    "breasts",
    "thighhighs",
    "skirt",
    "gamecg",
    "animalears",
    "foxgirl",
    "dress",
    "schooluniform",
    "twogirls",
    "gloves",
    "vocaloid",
    "touhou",
    "weapon",
    "withflowers",
    "pinkhair",
    "cloudsview",
    "white",
    "animal",
    "tail",
    "nude",
    "ponytail",
    "bed",
    "whitehair",
    "ribbons",
    "japanesecloths",
    "hatsuneAtlas",
    "bikini",
    "barefoot",
    "nobra",
    "food",
    "wings",
    "pantyhose",
    "openshirt",
    "headband",
    "penis",
    "close",
    "wet",
    "catgirl",
    "wolfgirl",
    "hneko",
    "hloli",
    "spreadlegs",
    "bra",
    "fateseries",
    "tree",
    "elbowgloves",
    "greenhair",
    "horns",
    "withpetals",
    "drunk",
    "cum",
    "headdress",
    "tie",
    "shorts",
    "hmaid",
    "headphones",
    "anusview",
    "Idol",
    "gun",
    "stockings",
    "tears",
    "breasthold",
    "necklace",
    "seethrough",
    "bunnyears",
    "bunnygirl",
    "topless",
    "beach",
    "erectnipples",
    "yuri",
    "vampire",
    "shirt",
    "pantypull",
    "tornclothes",
    "bondage",
    "demon",
    "bell",
    "shirtlift",
    "tattoo",
    "chain",
    "flatchest",
    "fingering",
  ],
  desc: "Hentai picture of anime waifus",
  start: async (Atlas, m, { prefix, pushName, doReact, inputCMD }) => {
    if (inputCMD == "nsfwmenu") {
      await doReact("🔞");
      let ntext = `\n╭────ꕥ NSFW Menu ꕥ────╮
├
├・ 💦 xᴠɪᴅᴇᴏꜱ <ᴀɴʏ ꜱᴇᴀʀᴄʜ ᴛᴇʀᴍ>
├・ 💦 ʜᴇɴᴛᴀɪᴠɪᴅᴇᴏ
├・ 💦 ᴘᴜꜱꜱʏ, ꜱᴘʀᴇᴀᴅᴘᴜꜱꜱʏ,
├・ 💦 ɢᴇɴꜱʜɪɴ, ꜱQᴜɪʀᴛ,
├・ 💦 ɢʟᴀꜱꜱᴇꜱ, ꜱᴜɴɢʟᴀꜱꜱᴇꜱ,
├・ 💦 ꜱᴡɪᴍꜱᴜɪᴛ, ꜱᴄʜᴏᴏʟꜱᴡɪᴍꜱᴜɪᴛ,
├・ 💦 ʜᴏʟᴏʟɪᴠᴇ, ᴀꜱꜱ,
├・ 💦 ᴜɴᴅᴇʀᴡᴇᴀʀ, ɴɪᴘᴘʟᴇꜱ,
├・ 💦 ᴜɴᴄᴇɴꜱᴏʀᴇᴅ, ɴɪᴘᴘʟᴇꜱ,
├・ 💦 ᴜɴᴄᴇɴꜱᴏʀᴇᴅ, ꜱᴇx,
├・ 💦 ꜱᴇx2, ꜱᴇx3,
├・ 💦 ʙʟᴏɴᴅᴇ, ᴛᴡɪɴᴛᴀɪʟꜱ,
├・ 💦 ʙʀᴇᴀꜱᴛꜱ, ᴛʜɪɢʜʜɪɢʜꜱ,
├・ 💦 ꜱᴋɪʀᴛ, ɢᴀᴍᴇᴄɢ,
├・ 💦 ᴀɴɪᴍᴀʟᴇᴀʀꜱ, ꜰᴏxɢɪʀʟ,
├・ 💦 ᴅʀᴇꜱꜱ, ꜱᴄʜᴏᴏʟᴜɴɪꜰᴏʀᴍ,
├・ 💦 ᴛᴡᴏɢɪʀʟꜱ, ɢʟᴏᴠᴇꜱ,
├・ 💦 ᴠᴏᴄᴀʟᴏɪᴅ, ᴛᴏᴜʜᴏᴜ,
├・ 💦 ᴡᴇᴀᴘᴏɴ, ᴡɪᴛʜꜰʟᴏᴡᴇʀꜱ,
├・ 💦 ᴘɪɴᴋʜᴀɪʀ, ᴄʟᴏᴜᴅꜱᴠɪᴇᴡ,
├・ 💦 ᴡʜɪᴛᴇ, ᴀɴɪᴍᴀʟ,
├・ 💦 ᴛᴀɪʟ, ɴᴜᴅᴇ,
├・ 💦 ᴘᴏɴʏᴛᴀɪʟ, ʙᴇᴅ,
├・ 💦 ᴡʜɪᴛᴇ ʜᴀɪʀ, ʀɪʙʙᴏɴꜱ,
├・ 💦 ᴊᴀᴘᴀɴᴇꜱᴇᴄʟᴏᴛʜꜱ, 
├・ 💦 ʜᴀᴛꜱᴜɴᴇᴍɪᴋᴜ,
├・ 💦 ʙɪᴋɪɴɪ, ʙᴀʀᴇꜰᴏᴏᴛ,
├・ 💦 ɴᴏʙʀᴀ, ꜰᴏᴏᴅ,
├・ 💦 ᴡɪɴɢꜱ, ᴘᴀɴᴛʏʜᴏꜱᴇ,
├・ 💦 ᴏᴘᴇɴꜱʜɪʀᴛ, ʜᴇᴀᴅʙᴀɴᴅ,
├・ 💦 ᴘᴇɴɪꜱ, ᴄʟᴏꜱᴇ,
├・ 💦 ᴡᴇᴛ, ᴄᴀᴛɢɪʀʟ,
├・ 💦 ᴡᴏʟꜰɢɪʀʟ, ɴᴇᴋᴏ,
├・ 💦 ʟᴏʟɪ, ꜱᴘʀᴇᴀᴅʟᴇɢꜱ,
├・ 💦 ʙʀᴀ, ꜰᴀᴛᴇꜱᴇʀɪᴇꜱ,
├・ 💦 ᴛʀᴇᴇ, ᴇʟʙᴏᴡɢʟᴏᴠᴇꜱ,
├・ 💦 ɢʀᴇᴇɴʜᴀɪʀ, ʜᴏʀɴꜱ,
├・ 💦 ᴡɪᴛʜᴘᴇᴛᴀʟꜱ, ᴅʀᴜɴᴋ,
├・ 💦 ᴄᴜᴍ, ʜᴇᴀᴅ ᴅʀᴇꜱꜱ,
├・ 💦 ᴛɪᴇ, ꜱʜᴏʀᴛꜱ,
├・ 💦 ᴍᴀɪᴅ, ʜᴇᴀᴅᴘʜᴏɴᴇꜱ,
├・ 💦 ᴀɴᴜꜱᴠɪᴇᴡ, ɪᴅᴏʟ,
├・ 💦 ɢᴜɴ, ꜱᴛᴏᴄᴋɪɴɢꜱ,
├・ 💦 ᴛᴇᴀʀꜱ, ʙʀᴇᴀꜱᴛʜᴏʟᴅ,
├・ 💦 ɴᴇᴄᴋʟᴀᴄᴇ, ꜱᴇᴇᴛʜʀᴏᴜɢʜ,
├・ 💦 ʙᴜɴɴʏᴇᴀʀꜱ, ʙᴜɴɴʏɢɪʀʟ,
├・ 💦 ᴛᴏᴘʟᴇꜱꜱ, ʙᴇᴀᴄʜ,
├・ 💦 ᴇʀᴇᴄᴛɴɪᴘᴘʟᴇꜱ, ʏᴜʀɪ,
├・ 💦 ᴠᴀᴍᴘɪʀᴇ, ꜱʜɪʀᴛ,
├・ 💦 ᴘᴀɴᴛʏᴘᴜʟʟ, ᴛᴏʀɴᴄʟᴏᴛʜᴇꜱ,
├・ 💦 ʙᴏɴᴅᴀɢᴇ, ᴅᴇᴍᴏɴ,
├・ 💦 ʙᴇʟʟ, ꜱʜɪʀᴛʟɪꜰᴛ,
├・ 💦 ᴛᴀᴛᴛᴏᴏ, ᴄʜᴀɪɴ,
├・ 💦 ꜰʟᴀᴛᴄʜᴇꜱᴛ, ꜰɪɴɢᴇʀɪɴɢ 
├
╰──────────────────╯\n\n
🎀 Powered By: *FantoX APIs* 🎀\n\n*🧩 API link:* \n❖ https://github.com/FantoX001/Scrappy-API\n❖ https://fantox-api.vercel.app\n`;

      return Atlas.sendMessage(
        m.from,
        { image: { url: botImage5 }, caption: ntext },
        { quoted: m }
      );
    }

    let commands = inputCMD;
    await doReact("🔞");
    //if (NSFWstatus == "false") return m.reply(`This group is not NSFW enabled!\n\nTo configure NSFW mode, type:\n\n*${prefix}nsfw*`);

    m.reply("Chotto Matte...");

    let res = await axios.get(`https://fantox-apis.vercel.app/${commands}`);
    let hUrl = res.data.url;

    let neko = {
      image: { url: hUrl },
      caption: `*Yamatte kudasai ${pushName} onichaan!!*`,
      headerType: 4,
    };

    await Atlas.sendMessage(m.from, neko, { quoted: m }).catch((err) => {
      return "Error!";
    });
  },
};
